### ISSUE TITLE
feat: добавить ссылку на анкету для вступления в сообщество

### ISSUE THREAD

**Issue by EmmaMaltseva** [move-fast-and-break-things/movefastandbreakthings.club#15]
https://tally.so/r/

**Comment by yurijmikhalevich** [comment]
Анкету временно закрыл. Возможно, её надо будет перенести на google forms. На сайт можно добавить ссылку на эту страницу: https://github.com/move-fast-and-break-things/movefastandbreakthings.club/issues. И предложить открыть новую Issue с описанием почему ты хочешь вступить в сообщество :) По-программистски. Потом, вероятно, изменим это.
