### ISSUE TITLE
fix: Блокирует запрос Jquery файла

### ISSUE THREAD

**Issue by PlutoniumSoup** [move-fast-and-break-things/movefastandbreakthings.club#19]
![image](https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/145541424/77e68d04-c25b-4fb4-b0ae-0d11c0a55d98)

Справа снизу должна появляться кнопка, которая прокручивает страницу наверх
![image](https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/145541424/4d602c1f-f2a9-4bab-a2a9-b0405b41008b)

**Comment by yurijmikhalevich** [comment]
@PlutoniumSoup, нужно грузить jQuery с `https`, а не с `http` URL. Можешь поменять и в отдельном PR отправить.
