### ISSUE TITLE
fix: сделать лого кликабельным

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/movefastandbreakthings.club#2]
При клике на лого страница должна прокручиваться на самый верх. Если она уже на верху, то ничего не должно происходить.

<img width="1496" alt="Screenshot 2023-10-03 at 23 07 31" src="https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/4187729/49233d6a-33ba-493f-966e-4f40fdb25136">

**Comment by Katherine-Ya23** [comment]
Хочу попробовать поработать над этим 😵‍💫

**Comment by yurijmikhalevich** [comment]
@Katherine-Ya23, надо ещё сделать логотип в подвале кликабельным.
