### ISSUE TITLE
fix: сделать имена авторов кликабельными

### ISSUE THREAD

**Issue by yurijmikhalevich** [move-fast-and-break-things/movefastandbreakthings.club#3]
Имя автора должно вести на профиль автора в GitHub.

<img width="1148" alt="Screenshot 2023-10-03 at 23 10 15" src="https://github.com/move-fast-and-break-things/movefastandbreakthings.club/assets/4187729/cfdb9033-c1ab-42f4-9b25-1b5282fb83fa">

**Comment by 1mTaKoW** [comment]
Nice

**Comment by yurijmikhalevich** [comment]
Closed in #21
